language:
  english:
    every: "Every "
    every_month_of: "Every Month Of "
    every_day: " Every Day"
    onn : " On "
    on_month_of: " On Month Of "
    at_every_minute: " At Every Minute"
    at_every_minute_of_hour: " At Every Minute Of Hour "
    at : " At "
    and: " & "
    to: " to "
    sunday: "Sunday"
    monday: "Monday"
    tuesday: "Tuesday"
    wednesday: "Wednesday"
    thursday: "Thursday"
    friday: "Friday"
    saturday: "Saturday"
    january: "January"
    february: "February"
    march: "March"
    april: "April"
    may: "May"
    june: "June"
    july: "July"
    august: "August"
    september: "September"
    october: "October"
    november: "November"
    december: "December"
  bangla:
    every: "প্রতি "
    every_month_of: "প্রতি মাস:"
    every_day: " প্রতিদিন"
    onn : " "
    on_month_of: " মাস:"
    at_every_minute: " প্রতি মিনিটে "
    at_every_minute_of_hour: " প্রতি মিনিট ঘন্টা: "
    at : " সময় "
    and: " এবং "
    to: " থেকে "
    sunday: "রবিবার"
    monday: "সোমবার"
    tuesday: "মঙ্গলবার"
    wednesday: "বুধবার"
    thursday: "বৃহস্পতিবার"
    friday: "শুক্রবার"
    saturday: "শনিবার"
    january: "জানুয়ারীতে"
    february: "ফেব্রুয়ারীতে"
    march: "মার্চে"
    april: "এপ্রিলে"
    may: "মে"
    june: "জুনে"
    july: "জুলাই তে"
    august: "আগস্টে"
    september: "সেপ্টেম্বরে"
    october: "অক্টোবরে"
    november: "নভেম্বরে"
    december: "ডিসেম্বরে"
