apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: crontalk-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crontalk
  template:
    metadata:
      labels:
        app: crontalk
    spec:
      containers:
      - name: crontalk-container
        image: anondo123/crontalk:latest
        ports:
          - containerPort: 8008
            name: crontalk-port

---
apiVersion: v1
kind: Service
metadata:
  name: crontalk-service
spec:
  selector:
    app: crontalk
  ports:
  - protocol: TCP
    targetPort: crontalk-port
    port: 8008
    name: httpport
  type: LoadBalancer
